package mensajeriahibernate;
// Generated 08-nov-2015 18:40:58 by Hibernate Tools 4.3.1



/**
 * Historial generated by hbm2java
 */
public class Historial  implements java.io.Serializable {


     private int idHistorial;
     private Usuario usuario;
     private char tipoConsulta;
     private String fecha;

    public Historial() {
    }

    public Historial(int idHistorial, Usuario usuario, char tipoConsulta, String fecha) {
       this.idHistorial = idHistorial;
       this.usuario = usuario;
       this.tipoConsulta = tipoConsulta;
       this.fecha = fecha;
    }
    public String convertirHora(String hora1)
    {
        String hora;
        hora = ""+hora1.charAt(6)+hora1.charAt(7)+"/"+hora1.charAt(4)+hora1.charAt(5)+"/"+hora1.charAt(0)+hora1.charAt(1)+hora1.charAt(2)+hora1.charAt(3)+" "+hora1.charAt(8)+hora1.charAt(9)+":"+hora1.charAt(10)+hora1.charAt(11);

        return hora;
    }
   
    public int getIdHistorial() {
        return this.idHistorial;
    }
    
    public void setIdHistorial(int idHistorial) {
        this.idHistorial = idHistorial;
    }
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }
    public char getTipoConsulta() {
        return this.tipoConsulta;
    }
    
    public void setTipoConsulta(char tipoConsulta) {
        this.tipoConsulta = tipoConsulta;
    }
    public String getFecha() {
        return this.fecha;
    }
    
    public void setFecha(String fecha) {
        this.fecha = fecha;
    }




}


