package mensajeriahibernate;
// Generated 08-nov-2015 18:40:58 by Hibernate Tools 4.3.1



/**
 * Mensajes generated by hbm2java
 */
public class Mensajes  implements java.io.Serializable {


     private int idMensaje;
     private Usuario usuarioByEmisor;
     private Usuario usuarioByReceptor;
     private String texto;
     private String fecha;

    public Mensajes() {
    }

    public Mensajes(int idMensaje,String texto, Usuario usuarioByEmisor, Usuario usuarioByReceptor, String fecha) {
       this.idMensaje = idMensaje;
       this.usuarioByEmisor = usuarioByEmisor;
       this.usuarioByReceptor = usuarioByReceptor;
       this.texto = texto;
       this.fecha = fecha;
    }

    public String convertirHora(String hora1)
    {
        String hora;
        hora = ""+hora1.charAt(6)+hora1.charAt(7)+"/"+hora1.charAt(4)+hora1.charAt(5)+"/"+hora1.charAt(0)+hora1.charAt(1)+hora1.charAt(2)+hora1.charAt(3)+" "+hora1.charAt(8)+hora1.charAt(9)+":"+hora1.charAt(10)+hora1.charAt(11);

        return hora;
    }
    
    @Override
    public String toString() {
        return "Mensajes{" + "idMensaje=" + idMensaje + ", usuarioByEmisor=" + usuarioByEmisor.getUsuario() + ", usuarioByReceptor=" + usuarioByReceptor.getUsuario() + ", texto=" + texto + ", fecha=" + convertirHora(fecha) + '}';
    }
    
    
   
    public int getIdMensaje() {
        return this.idMensaje;
    }
    
    public void setIdMensaje(int idMensaje) {
        this.idMensaje = idMensaje;
    }
    public Usuario getUsuarioByEmisor() {
        return this.usuarioByEmisor;
    }
    
    public void setUsuarioByEmisor(Usuario usuarioByEmisor) {
        this.usuarioByEmisor = usuarioByEmisor;
    }
    public Usuario getUsuarioByReceptor() {
        return this.usuarioByReceptor;
    }
    
    public void setUsuarioByReceptor(Usuario usuarioByReceptor) {
        this.usuarioByReceptor = usuarioByReceptor;
    }
    public String getTexto() {
        return this.texto;
    }
    
    public void setTexto(String texto) {
        this.texto = texto;
    }
    public String getFecha() {
        return this.fecha;
    }
    
    public void setFecha(String fecha) {
        this.fecha = fecha;
    }




}


