package mensajeriahibernate;
// Generated 08-nov-2015 18:40:58 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Usuario generated by hbm2java
 */
public class Usuario  implements java.io.Serializable {


     private String usuario;
     private String nombre;
     private String password;
     private Set mensajesesForEmisor = new HashSet(0);
     private Set mensajesesForReceptor = new HashSet(0);
     private Set historials = new HashSet(0);
     private int mensajesEnviados=0;

    public int getMensajesEnviados() {
        return mensajesEnviados;
    }

    public void setMensajesEnviados(int mensajesEnviados) {
        this.mensajesEnviados = mensajesEnviados;
    }
     
     

    public Usuario() {
    }

    public Usuario(String usuario) {
        this.usuario = usuario;
    }

	
    public Usuario(String usuario, String nombre, String password) {
        this.usuario = usuario;
        this.nombre = nombre;
        this.password = password;
    }
    public Usuario(String usuario, String nombre, String password, Set mensajesesForEmisor, Set mensajesesForReceptor, Set historials) {
       this.usuario = usuario;
       this.nombre = nombre;
       this.password = password;
       this.mensajesesForEmisor = mensajesesForEmisor;
       this.mensajesesForReceptor = mensajesesForReceptor;
       this.historials = historials;
    }
   
    public String getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(String usuario) {
        this.usuario = usuario;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public Set getMensajesesForEmisor() {
        return this.mensajesesForEmisor;
    }
    
    public void setMensajesesForEmisor(Set mensajesesForEmisor) {
        this.mensajesesForEmisor = mensajesesForEmisor;
    }
    public Set getMensajesesForReceptor() {
        return this.mensajesesForReceptor;
    }
    
    public void setMensajesesForReceptor(Set mensajesesForReceptor) {
        this.mensajesesForReceptor = mensajesesForReceptor;
    }
    public Set getHistorials() {
        return this.historials;
    }
    
    public void setHistorials(Set historials) {
        this.historials = historials;
    }




}


